export const work = [
  {
    role: 'software engineer intern',
    company: 'i4Sight technologies',
    start: 'jun 2023',
    end: 'present',
    responsibilities: [
      'Refactor company Tower Buddy & i4sight websites',
      'Create and translate the UI design mock-ups into responsive design and scalable code from scratch using technologies like HTML, CSS, JavaScript, ReactJS library, and NPM packages',
      'Refactor towerbuddy webapp',
      'Create designs of website, icons, logos, and slides using popular UI/UX design and editing tools like Figma, Illustrator, and Photoshop',
      'Develop and maintain better code base for collaboration and version control on GitHub',
    ],
    type: 'remote',
    location: 'banaglore',
    links: ['https://towerbuddy.tel/', 'https://www.i4sight.net/'],
  },
  {
    role: 'data labelling specialist',
    company: 'sanp INC (snapchat)',
    start: 'jan 2023',
    end: 'jun 2023',
    responsibilities: [
      'Labelled images and tagged relevant information about the image to train AI and machine learning models',
      'Curated images methodically and selected images around a specific theme',
      'Annotated features and objects in images using a dedicated annotation tool provided by SnapChat',
      'Edited graphics and defined object boundaries',
    ],
    type: 'remote',
    location: 'bangalore',
    links: '',
  },
  {
    role: 'image editor',
    company: "hudson's bay company",
    start: 'nov 2022 ',
    end: 'jan 2023',
    responsibilities: [
      'Ensured all vendor-provided images were meeting the standards of the bay to go live on the site',
      'Retouched vendor-provided images from scratch as per The Bay guidelines',
      'Retouched in-house-shot images and ensured that all the images fulfilled the requirements and followed the guidelines',
      'Assured the quality of the images provided by the business partners',
    ],
    type: 'hybrid',
    location: 'bangalore',
    links: '',
  },
  {
    role: 'digital imager',
    company: 'target corporation',
    start: 'mar 2021',
    end: 'oct 2022',
    responsibilities: [
      'Retouched products, apparel, accessories, on-figure model images, and still-life CGI images for Target.com, weekly ads, and other Target properties',
      'Followed creative direction from the art director and senior artists and followed complex and detailed notes to create high-quality creative assets',
      'Delivered daily targets without compromising overall image quality in a fast-paced, rapidly changing environment under strict deadlines',
      'As an independent contributor, I was responsible for making creative decisions based on brand guidelines',
    ],
    type: 'hybrid',
    location: 'bangalore',
    links: '',
  },
  {
    role: 'imager editor',
    company: 'flipkart Pvt Ltd',
    start: 'aug 2019',
    end: 'mar 2022',
    responsibilities: [
      'Analyzed photograph requirements from vendors to determine appropriate lighting, colour, tone, and overall aesthetic before editing',
      'Worked side by side with a senior photo editor to modify and enhance photographs to meet project specifications set forth by managers and clients',
      'Created infographics of products to demonstrate the features and functionalities of the product',
    ],
    type: 'on-sight',
    location: 'bangalore',
    links: '',
  },
];
