export const work = [
  {
    role: "software engineer",
    company: "i4Sight technologies",
    start: "jun 2023",
    end: "july 2025",
    responsibilities: [
      "Transformed UI/UX mock-ups into responsive, interactive web interfaces using HTML, CSS, JavaScript, ReactJS, and NPM packages.",
      "Led end-to-end design, development, and deployment of company websites [TowerBuddy, i4SIGHT], enhancing online presence.",
      "Collaborated with backend teams to define, test, and integrate RESTful API endpoints, optimizing data flow and data handling using asynchronous JavaScript (async/await) for enhanced responsiveness.",
      "Partnered with marketing team to implement Google Tag Manager (GTM), Google Analytics (GA), and HubSpot forms on TowerBuddy for user behavior analysis and marketing insights.",
      "Boosted TowerBuddy’s website & web application Lighthouse scores (Performance 97, Accessibility 90, Best Practices 96, SEO 92) by optimizing code, accessibility, and load strategies.",
      "Spearheaded efficient Git/GitHub version control and team collaboration, ensuring code integrity and rapid development.",
      "Elevated UI aesthetics by crafting custom icons, logos, and visual assets using Figma, Adobe Illustrator, and Photoshop.",
    ],
    type: "hybrid",
    location: "banaglore",
  },
  {
    role: "web developer intern (part-time)",
    company: "MetaPouch Technologies Pvt Ltd",
    start: "feb 2023",
    end: "mar 2024",
    responsibilities: [
      "Contributed to the design, development, and management of the company’s product website (www.metapouch.io).",
      "Built responsive UI components ensuring improved functionality, performance, and user experience.",
      "Applied React.js, JavaScript (ES6+), HTML, CSS, and Tailwind CSS for front-end development tasks.",
      "Collaborated with the team to maintain and enhance product features in a part-time internship role.",
    ],
    type: "remote",
    location: "bangalore",
  },
  {
    role: "data labelling specialist",
    company: "sanp INC (snapchat)",
    start: "jan 2023",
    end: "jun 2023",
    responsibilities: [
      "Labelled images and tagged relevant information about the image to train AI and machine learning models",
      "Curated images methodically and selected images around a specific theme",
      "Annotated features and objects in images using a dedicated annotation tool provided by SnapChat",
      "Edited graphics and defined object boundaries",
    ],
    type: "remote",
    location: "bangalore",
  },
  {
    role: "image editor",
    company: "hudson's bay company",
    start: "nov 2022 ",
    end: "jan 2023",
    responsibilities: [
      "Ensured all vendor-provided images were meeting the standards of the bay to go live on the site",
      "Retouched vendor-provided images from scratch as per The Bay guidelines",
      "Retouched in-house-shot images and ensured that all the images fulfilled the requirements and followed the guidelines",
      "Assured the quality of the images provided by the business partners",
    ],
    type: "hybrid",
    location: "bangalore",
  },
  {
    role: "digital imager",
    company: "target corporation",
    start: "mar 2021",
    end: "oct 2022",
    responsibilities: [
      "Retouched products, apparel, accessories, on-figure model images, and still-life CGI images for Target.com, weekly ads, and other Target properties",
      "Followed creative direction from the art director and senior artists and followed complex and detailed notes to create high-quality creative assets",
      "Delivered daily targets without compromising overall image quality in a fast-paced, rapidly changing environment under strict deadlines",
      "As an independent contributor, I was responsible for making creative decisions based on brand guidelines",
    ],
    type: "hybrid",
    location: "bangalore",
  },
  {
    role: "imager editor",
    company: "flipkart Pvt Ltd",
    start: "aug 2019",
    end: "mar 2022",
    responsibilities: [
      "Analyzed photograph requirements from vendors to determine appropriate lighting, colour, tone, and overall aesthetic before editing",
      "Worked side by side with a senior photo editor to modify and enhance photographs to meet project specifications set forth by managers and clients",
      "Created infographics of products to demonstrate the features and functionalities of the product",
    ],
    type: "on-sight",
    location: "bangalore",
  },
];
